language: R
sudo: false
cache: packages
before_install:
- openssl aes-256-cbc -K $encrypted_93835e86f9b7_key -iv $encrypted_93835e86f9b7_iv
  -in tests/testthat/googlecalendar_token.rds.enc -out tests/testthat/googlecalendar_token.rds -d
